apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: deployment  # also supports daemonset or sidecar
  image: otel/opentelemetry-collector-contrib:0.128.0
  replicas: 2
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    
    processors:
      attributes/logs:
        actions:
          - key: metric_collector
            value: oltp
            action: insert
          - key: loki.attribute.labels
            value: appname, hostname 
            action: insert
      attributes/metrics:
        actions:
          - key: origin
            value: otel
            action: insert
      attributes/prometheus:
        actions:
          - key: metrics_collector
            value: prometheus
            action: insert
      attributes/otlp:
        actions:
          - key: metrics_collector
            value: otlp
            action: insert

    exporters:
      debug:
        verbosity: normal
      otlphttp/logs:
        endpoint: http://loki-gateway.observability/otlp
      prometheusremotewrite:
        endpoint: http://mimir-nginx.observability/api/v1/push
        tls:
          insecure: true

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    service:
      extensions:
      - health_check
      pipelines:
        metrics/otlp:
          receivers:
            - otlp
          processors:
            - attributes/metrics
            - attributes/otlp
          exporters:
            - debug
            - prometheusremotewrite
        logs/oltp:
          receivers:
            - otlp
          processors:
            - attributes/logs
          exporters:
            - debug
            - otlphttp/logs